# Generated by Django 4.2.1 on 2023-05-29 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('week9_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
