# Generated by Django 4.2.1 on 2023-05-29 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('week9_app', '0003_user_db'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_db',
            name='pass2',
        ),
    ]
