# Generated by Django 4.2.1 on 2023-05-30 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('week9_app', '0005_alter_user_db_pass1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.RenameField(
            model_name='user_db',
            old_name='pass1',
            new_name='password',
        ),
    ]
