# Generated by Django 4.2.1 on 2023-05-30 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('week9_app', '0006_delete_book_rename_pass1_user_db_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_db',
        ),
    ]
